// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpyh8VM5oVWap7uiJx6WcQu4J_N-DnDcE',
    appId: '1:721641140486:web:97cd65140d2dc12d72ae87',
    messagingSenderId: '721641140486',
    projectId: 'artisans-2e53d',
    authDomain: 'artisans-2e53d.firebaseapp.com',
    storageBucket: 'artisans-2e53d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBioUSYYP0jHLTaecIoskGiM3UA6GbkiNo',
    appId: '1:721641140486:android:b1d6d861b020ce2b72ae87',
    messagingSenderId: '721641140486',
    projectId: 'artisans-2e53d',
    storageBucket: 'artisans-2e53d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1n8ABbG3A6vDvNDg1bS1dJE2j5Lu75go',
    appId: '1:721641140486:ios:c7a0193de030dca172ae87',
    messagingSenderId: '721641140486',
    projectId: 'artisans-2e53d',
    storageBucket: 'artisans-2e53d.appspot.com',
    iosBundleId: 'com.example.artisans',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1n8ABbG3A6vDvNDg1bS1dJE2j5Lu75go',
    appId: '1:721641140486:ios:ca208ab5dcf2e02972ae87',
    messagingSenderId: '721641140486',
    projectId: 'artisans-2e53d',
    storageBucket: 'artisans-2e53d.appspot.com',
    iosBundleId: 'com.example.artisans.RunnerTests',
  );
}
